### ISSUE TITLE
Use LinuxInstallScript for Conda

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/PythonRefresher#2]
The students should be given a two-liner (`git clone` + `bash user/install.sh` from LinuxInstallScript) to get all the software ready to go so they don't need to install Conda manually, but they should still be made aware of how Conda works and how to make environments.

**Comment by cornehappy** [comment]
could your script simply replace this first block of code in the manual? ![image](https://user-images.githubusercontent.com/45964873/50282680-ddb60100-0453-11e9-839f-9923202d2b71.png)

if so, students have conda and simply start using conda (also setting up themselves a environment) in the blocks after that. That is something students should be able to do I would say.

**Comment by GreatEmerald** [comment]
Yes, that's what I think too, also giving a link to the docs for setting it up manually for those who want to do so.

But the latter sections explain how to add new environments; we could either leave them as-is, or explain what exactly the install script did. Maybe it's easiest to just leave them as-is, though, and just say that the environment called `geoscripting` was made for them, so they don't have to.

**Comment by cornehappy** [comment]
be aware that they create in module 11 another environment themselves!

**Comment by GreatEmerald** [comment]
Yes, that will need to be changed as well.
